repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: Fix Import Order
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
        name: Run Black
    -   id: black-jupyter
        name: Run Black on Jupyter Notebooks
